export const EDIFY_BASE = "https://tienda.edify.com.ar";
export const DELAY_MS = 1500;

export const CATEGORY_MAP: Record<string, string> = {
  "metalurgico": "Chapas, Tejas, Losas y Zinguerías",
  "metalurgico/chapas-galvanizadas": "Chapas, Tejas, Losas y Zinguerías",
  "metalurgico/hierro": "Hierros, Mallas, Alambres, Tornillos, Clavos, Cercos",
  "metalurgico/malla": "Hierros, Mallas, Alambres, Tornillos, Clavos, Cercos",
  "metalurgico/correas-metalicas": "Chapas, Tejas, Losas y Zinguerías",
  "metalurgico/perfiles": "Hierros, Mallas, Alambres, Tornillos, Clavos, Cercos",
  "construccion-en-seco": "Construcción en Seco",
  "construccion-en-seco/cintas-de-papel": "Construcción en Seco",
  "construccion-en-seco/cintas-tramadas": "Construcción en Seco",
  "construccion-en-seco/rollos-y-aislacion": "Construcción en Seco",
  "construccion-en-seco/masillas-p-superboard": "Construcción en Seco",
  "construccion-en-seco/masillas-p-durlock": "Construcción en Seco",
  "construccion-en-seco/placas-durlock": "Construcción en Seco",
  "construccion-en-seco/perfileria-estructural": "Construcción en Seco",
  "construccion-en-seco/piso-flotante": "Construcción en Seco",
  "construccion-en-seco/perfileria-desmontable": "Construcción en Seco",
  "construccion-en-seco/molduras": "Construcción en Seco",
  "construccion-en-seco/placas-superboard": "Construcción en Seco",
  "construccion-en-seco/tablillas-pvc": "Construcción en Seco",
  "construccion-en-seco/tornilleria": "Herramientas",
  "corralon": "Cales, Cementos, Finos, Pegamentos, Pastina y Hormigones",
  "corralon/cemento": "Cales, Cementos, Finos, Pegamentos, Pastina y Hormigones",
  "corralon/hidrofugo": "Cales, Cementos, Finos, Pegamentos, Pastina y Hormigones",
  "corralon/ladrillos-ceramicos": "Ladrillos y Bloques",
  "corralon/cal": "Cales, Cementos, Finos, Pegamentos, Pastina y Hormigones",
  "corralon/ladrillos": "Ladrillos y Bloques",
  "corralon/rollos-y-aislacion": "Construcción en Seco",
  "corralon/anclaje": "Herramientas",
  "corralon/ladrillos-refractarios": "Ladrillos y Bloques",
  "banos-y-griferias": "Sanitarios y Griferías",
  "banos-y-griferias/tanques": "Sanitarios y Griferías",
  "banos-y-griferias/artefactos-losa": "Sanitarios y Griferías",
  "banos-y-griferias/asientos-p-inodoro": "Sanitarios y Griferías",
  "banos-y-griferias/termotanques": "Sanitarios y Griferías",
  "banos-y-griferias/juegos-de-griferia": "Sanitarios y Griferías",
  "adhesivos": "Cales, Cementos, Finos, Pegamentos, Pastina y Hormigones",
  "adhesivos/adhesivos-p-ceramicos": "Suelos y Revestimientos",
  "adhesivos/membrana": "Aditivos, Impermeabilizaciones y Aislaciones",
  "adhesivos/revoque": "Cales, Cementos, Finos, Pegamentos, Pastina y Hormigones",
  "adhesivos/guardacantos": "Suelos y Revestimientos",
  "pisos": "Suelos y Revestimientos",
  "pisos/ceramicos": "Suelos y Revestimientos",
  "pisos/porcelanatos": "Suelos y Revestimientos",
  "tubos-y-accesorios-sanitarios": "Instalaciones Sanitarias",
  "tubos-y-accesorios-sanitarios/canaletas-pvc": "Instalaciones Sanitarias",
  "tubos-y-accesorios-sanitarios/membrana": "Aditivos, Impermeabilizaciones y Aislaciones",
  "tubos-y-accesorios-sanitarios/accesorios-ppn-fusion": "Instalaciones Sanitarias",
  "tubos-y-accesorios-sanitarios/tubos-polietileno": "Instalaciones Sanitarias",
  "tubos-y-accesorios-sanitarios/tubos-pvc": "Instalaciones Sanitarias",
  "tubos-y-accesorios-sanitarios/revestimientos-plasticos": "Instalaciones Sanitarias",
};
